'use client';

import React, { useState } from 'react';

export default function Home() {
  const [tab, setTab] = useState('home');

    return (
        <div style={{
              maxWidth: '420px',
                    margin: '0 auto',
                          minHeight: '100vh',
                                backgroundColor: '#f8fafc',
                                      color: '#1e293b',
                                            fontFamily: 'sans-serif',
                                                  paddingBottom: '80px',
                                                        position: 'relative',
                                                              boxSizing: 'border-box'
                                                                  }}>
                                                                        {/* ヘッダー */}
                                                                              <header style={{
                                                                                      backgroundColor: '#0f172a',
                                                                                              color: '#ffffff',
                                                                                                      padding: '16px',
                                                                                                              display: 'flex',
                                                                                                                      justifyContent: 'space-between',
                                                                                                                              alignItems: 'center'
                                                                                                                                    }}>
                                                                                                                                            <h1 style={{ margin: 0, fontSize: '16px', fontWeight: 'bold' }}>🏠 共有家計簿 & 経費</h1>
                                                                                                                                                    <span style={{ fontSize: '12px', backgroundColor: '#334155', padding: '4px 8px', borderRadius: '4px' }}>2026/09 ▼</span>
                                                                                                                                                          </header>

                                                                                                                                                                {/* メインコンテンツ */}
                                                                                                                                                                      <main style={{ padding: '16px' }}>
                                                                                                                                                                              {/* 支出区分サマリー */}
                                                                                                                                                                                      <div style={{ backgroundColor: '#ffffff', padding: '16px', borderRadius: '12px', border: '1px solid #e2e8f0', marginBottom: '16px' }}>
                                                                                                                                                                                                <div style={{ fontSize: '12px', fontWeight: 'bold', color: '#64748b', marginBottom: '8px' }}>今月の支出区分</div>
                                                                                                                                                                                                          <div style={{ display: 'flex', gap: '8px', textAlign: 'center' }}>
                                                                                                                                                                                                                      <div style={{ flex: 1, backgroundColor: '#eff6ff', padding: '8px', borderRadius: '8px' }}>
                                                                                                                                                                                                                                    <span style={{ fontSize: '10px', color: '#2563eb', display: 'block', fontWeight: 'bold' }}>生活費</span>
                                                                                                                                                                                                                                                  <span style={{ fontSize: '13px', fontWeight: 'bold' }}>¥84,200</span>
                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                          <div style={{ flex: 1, backgroundColor: '#fffbeb', padding: '8px', borderRadius: '8px' }}>
                                                                                                                                                                                                                                                                                        <span style={{ fontSize: '10px', color: '#d97706', display: 'block', fontWeight: 'bold' }}>固定費</span>
                                                                                                                                                                                                                                                                                                      <span style={{ fontSize: '13px', fontWeight: 'bold' }}>¥44,250</span>
                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                              <div style={{ flex: 1, backgroundColor: '#faf5ff', padding: '8px', borderRadius: '8px' }}>
                                                                                                                                                                                                                                                                                                                                            <span style={{ fontSize: '10px', color: '#9333ea', display: 'block', fontWeight: 'bold' }}>事業経費</span>
                                                                                                                                                                                                                                                                                                                                                          <span style={{ fontSize: '13px', fontWeight: 'bold' }}>¥12,800</span>
                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                {/* 支払者サマリー */}
                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ backgroundColor: '#ffffff', padding: '16px', borderRadius: '12px', border: '1px solid #e2e8f0', marginBottom: '16px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ fontSize: '12px', fontWeight: 'bold', color: '#64748b', marginBottom: '8px' }}>今月の支払者内訳</div>
                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 0', borderBottom: '1px solid #f1f5f9', fontSize: '14px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>👤 Keisuke</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span style={{ fontWeight: 'bold' }}>¥98,450</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 0', fontSize: '14px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span>👤 パートナー</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span style={{ fontWeight: 'bold' }}>¥42,800</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* 履歴リスト */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ backgroundColor: '#ffffff', padding: '16px', borderRadius: '12px', border: '1px solid #e2e8f0' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ fontSize: '12px', fontWeight: 'bold', color: '#64748b', marginBottom: '8px' }}>最近の登録</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '14px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ fontWeight: 'bold' }}>杏林堂 <span style={{ fontSize: '10px', backgroundColor: '#f1f5f9', padding: '2px 4px', borderRadius: '4px', color: '#475569' }}>日用品 / クレカ</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ fontSize: '11px', color: '#94a3b8' }}>09/08 ・ 払: Keisuke</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span style={{ fontWeight: 'bold' }}>¥3,461</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* ナビゲーション */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <nav style={{ position: 'fixed', bottom: 0, left: 0, right: 0, maxWidth: '420px', margin: '0 auto', backgroundColor: '#0f172a', color: '#ffffff', display: 'flex', justifyContent: 'space-around', padding: '12px 0', borderTop: '1px solid #1e293b' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={() => setTab('home')} style={{ background: 'none', border: 'none', color: tab === 'home' ? '#38bdf8' : '#94a3b8', fontWeight: tab === 'home' ? 'bold' : 'normal' }}>📊 ホーム</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={() => setTab('entry')} style={{ background: 'none', border: 'none', color: tab === 'entry' ? '#38bdf8' : '#94a3b8', fontWeight: tab === 'entry' ? 'bold' : 'normal' }}>📸 登録</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={() => setTab('search')} style={{ background: 'none', border: 'none', color: tab === 'search' ? '#38bdf8' : '#94a3b8', fontWeight: tab === 'search' ? 'bold' : 'normal' }}>🔍 検索</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={() => setTab('chart')} style={{ background: 'none', border: 'none', color: tab === 'chart' ? '#38bdf8' : '#94a3b8', fontWeight: tab === 'chart' ? 'bold' : 'normal' }}>📈 分析</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      